import type { ThemeDefinition } from 'vuetify'





export const staticPrimaryColor = '#0066CC'
export const staticPrimaryDarkenColor = '#003366'
export const staticSuccessColor = '#00AA66'
export const staticWarningColor = '#FF9900'
export const staticErrorColor = '#CC3333'

export const themes: Record<string, ThemeDefinition> = {
  light: {
    dark: false,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#FFFFFF',
      'primary-darken-1': staticPrimaryDarkenColor,
      'primary-light': '#3399FF',

      'secondary': staticPrimaryDarkenColor,
      'on-secondary': '#FFFFFF',
      'secondary-darken-1': '#001A4D',
      'secondary-light': '#1A4D99',
      'avatar-initials': '#0066CC',
      'on-avatar-initials': '#FFFFFF',
      'success': staticSuccessColor,
      'on-success': '#FFFFFF',
      'success-darken-1': '#007744',
      'success-light': '#33CC99',
      'info': '#0066CC',
      'on-info': '#FFFFFF',
      'info-darken-1': '#003366',
      'info-light': '#3399FF',
      'warning': staticWarningColor,
      'on-warning': '#FFFFFF',
      'warning-darken-1': '#CC7700',
      'warning-light': '#FFBB33',
      'error': staticErrorColor,
      'on-error': '#FFFFFF',
      'error-darken-1': '#991111',
      'error-light': '#FF6666',

      'background': '#F5F7FA',
      'on-background': '#1A1F36',
      'surface': '#FFFFFF',
      'on-surface': '#1A1F36',

      'surface-variant': '#E8EEF5',
      'on-surface-variant': '#42526B',
      'surface-light': '#F0F4FA',
      'surface-bright': '#FFFFFF',
      'grey-50': '#FFFFFF',
      'grey-100': '#F5F7FA',
      'grey-200': '#E8EEF5',
      'grey-300': '#D4DDEA',
      'grey-400': '#B5C5DB',
      'grey-500': '#8B9FBD',
      'grey-600': '#5F7A9E',
      'grey-700': '#42526B',
      'grey-800': '#2A3548',
      'grey-900': '#1A1F36',
      'grey-light': '#F5F7FA',
      'perfect-scrollbar-thumb': '#B5C5DB',
      'skin-bordered-background': '#FFFFFF',
      'skin-bordered-surface': '#FFFFFF',
      'expansion-panel-text-custom-bg': '#F5F7FA',
    },

    variables: {
      'code-color': '#0066CC',
      'overlay-scrim-background': '#1A1F36',
      'tooltip-background': '#1A1F36',
      'overlay-scrim-opacity': 0.5,
      'hover-opacity': 0.04,
      'focus-opacity': 0.08,
      'selected-opacity': 0.06,
      'activated-opacity': 0.08,
      'pressed-opacity': 0.10,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.4,
      'border-color': '#D4DDEA',
      'border-opacity': 1,
      'table-header-color': '#FFFFFF',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,
      'switch-opacity': 0.2,
      'switch-disabled-track-opacity': 0.3,
      'switch-disabled-thumb-opacity': 0.4,
      'switch-checked-disabled-opacity': 0.3,
      'track-bg': '#E8EEF5',
      'chat-bg': '#FFFFFF',
      'shadow-key-umbra-color': '#1A1F36',
      'shadow-xs-opacity': 0,
      'shadow-sm-opacity': 0.02,
      'shadow-md-opacity': 0.03,
      'shadow-lg-opacity': 0.04,
      'shadow-xl-opacity': 0.05,
    },
  },
  dark: {
    dark: true,
    colors: {
      'primary': '#3399FF',
      'on-primary': '#FFFFFF',
      'primary-darken-1': staticPrimaryDarkenColor,
      'primary-light': '#66B2FF',

      'secondary': '#1A4D99',
      'on-secondary': '#FFFFFF',
      'secondary-darken-1': '#001A4D',
      'secondary-light': '#3366CC',
      'avatar-initials': '#3399FF',
      'on-avatar-initials': '#FFFFFF',
      'success': '#33CC99',
      'on-success': '#FFFFFF',
      'success-darken-1': '#1A8866',
      'success-light': '#66DDAA',
      'info': '#3399FF',
      'on-info': '#FFFFFF',
      'info-darken-1': '#1A66CC',
      'info-light': '#66B2FF',
      'warning': '#FFBB33',
      'on-warning': '#FFFFFF',
      'warning-darken-1': '#CC8800',
      'warning-light': '#FFD166',
      'error': '#FF6666',
      'on-error': '#FFFFFF',
      'error-darken-1': '#CC2222',
      'error-light': '#FF9999',

      'background': '#0A0E1A',
      'on-background': '#E8ECFB',
      'surface': '#141B2B',
      'on-surface': '#E8ECFB',

      'surface-variant': '#22304A',
      'on-surface-variant': '#C5D0E8',
      'surface-light': '#1A2638',
      'surface-bright': '#22304A',
      'grey-50': '#141B2B',
      'grey-100': '#1A2638',
      'grey-200': '#22304A',
      'grey-300': '#2E3E5A',
      'grey-400': '#475569',
      'grey-500': '#64748B',
      'grey-600': '#94A3B8',
      'grey-700': '#CBD5E1',
      'grey-800': '#E2E8F0',
      'grey-900': '#E8ECFB',
      'grey-light': '#1A2638',
      'perfect-scrollbar-thumb': '#2E3E5A',
      'skin-bordered-background': '#141B2B',
      'skin-bordered-surface': '#141B2B',
    },
    variables: {
      'code-color': '#66B2FF',
      'overlay-scrim-background': '#000000',
      'tooltip-background': '#000000',
      'overlay-scrim-opacity': 0.7,
      'hover-opacity': 0.10,
      'focus-opacity': 0.14,
      'selected-opacity': 0.12,
      'activated-opacity': 0.14,
      'pressed-opacity': 0.16,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.38,
      'border-color': '#2E3E5A',
      'border-opacity': 1,
      'table-header-color': '#141B2B',
      'high-emphasis-opacity': 1,
      'medium-emphasis-opacity': 0.87,
      'switch-opacity': 0.4,
      'switch-disabled-track-opacity': 0.4,
      'switch-disabled-thumb-opacity': 0.8,
      'switch-checked-disabled-opacity': 0.3,
      'track-bg': '#22304A',
      'chat-bg': '#141B2B',
      'shadow-key-umbra-color': '#000000',
      'shadow-xs-opacity': 0,
      'shadow-sm-opacity': 0.04,
      'shadow-md-opacity': 0.05,
      'shadow-lg-opacity': 0.06,
      'shadow-xl-opacity': 0.08,
    },
  },
}

export default themes
