/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'access-control-permissions': RouteRecordInfo<'access-control-permissions', '/access-control/permissions', Record<never, never>, Record<never, never>>,
    'access-control-roles': RouteRecordInfo<'access-control-roles', '/access-control/roles', Record<never, never>, Record<never, never>>,
    'ai-assistant': RouteRecordInfo<'ai-assistant', '/ai/assistant', Record<never, never>, Record<never, never>>,
    'ai-knowledge': RouteRecordInfo<'ai-knowledge', '/ai/knowledge', Record<never, never>, Record<never, never>>,
    'ai-knowledge-id': RouteRecordInfo<'ai-knowledge-id', '/ai/knowledge/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'ai-knowledge-new': RouteRecordInfo<'ai-knowledge-new', '/ai/knowledge/new', Record<never, never>, Record<never, never>>,
    'ai-skills': RouteRecordInfo<'ai-skills', '/ai/skills', Record<never, never>, Record<never, never>>,
    'c-chatId': RouteRecordInfo<'c-chatId', '/c/:chatId', { chatId: ParamValue<true> }, { chatId: ParamValue<false> }>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'integrations': RouteRecordInfo<'integrations', '/integrations', Record<never, never>, Record<never, never>>,
    'integrations-gateway': RouteRecordInfo<'integrations-gateway', '/integrations/gateway', Record<never, never>, Record<never, never>>,
    'integrations-mcp': RouteRecordInfo<'integrations-mcp', '/integrations/mcp', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'pages-account-settings-tab': RouteRecordInfo<'pages-account-settings-tab', '/pages/account-settings/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'pages-misc-coming-soon': RouteRecordInfo<'pages-misc-coming-soon', '/pages/misc/coming-soon', Record<never, never>, Record<never, never>>,
    'pages-misc-under-maintenance': RouteRecordInfo<'pages-misc-under-maintenance', '/pages/misc/under-maintenance', Record<never, never>, Record<never, never>>,
    'pages-user-profile-tab': RouteRecordInfo<'pages-user-profile-tab', '/pages/user-profile/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'security-credentials': RouteRecordInfo<'security-credentials', '/security/credentials', Record<never, never>, Record<never, never>>,
    'tenants': RouteRecordInfo<'tenants', '/tenants', Record<never, never>, Record<never, never>>,
  }
}
